// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/executor/executor.proto

package crocodile_srv_executor

import (
	job "crocodile/service/job/proto/job"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 订阅消息
type ExecuteMsg struct {
	// 任务的事件类型 执行任务杀死任务
	Event int32 `protobuf:"varint,1,opt,name=event,proto3" json:"event,omitempty"`
	// 任务的详细信息
	Task *job.Task `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	// 执行任务的主机IP
	Runhost              string   `protobuf:"bytes,3,opt,name=runhost,proto3" json:"runhost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteMsg) Reset()         { *m = ExecuteMsg{} }
func (m *ExecuteMsg) String() string { return proto.CompactTextString(m) }
func (*ExecuteMsg) ProtoMessage()    {}
func (*ExecuteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_67db812d605d77b3, []int{0}
}

func (m *ExecuteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteMsg.Unmarshal(m, b)
}
func (m *ExecuteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteMsg.Marshal(b, m, deterministic)
}
func (m *ExecuteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteMsg.Merge(m, src)
}
func (m *ExecuteMsg) XXX_Size() int {
	return xxx_messageInfo_ExecuteMsg.Size(m)
}
func (m *ExecuteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteMsg proto.InternalMessageInfo

func (m *ExecuteMsg) GetEvent() int32 {
	if m != nil {
		return m.Event
	}
	return 0
}

func (m *ExecuteMsg) GetTask() *job.Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *ExecuteMsg) GetRunhost() string {
	if m != nil {
		return m.Runhost
	}
	return ""
}

func init() {
	proto.RegisterType((*ExecuteMsg)(nil), "crocodile.srv.executor.ExecuteMsg")
}

func init() { proto.RegisterFile("proto/executor/executor.proto", fileDescriptor_67db812d605d77b3) }

var fileDescriptor_67db812d605d77b3 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xad, 0x48, 0x4d, 0x2e, 0x2d, 0xc9, 0x2f, 0x82, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0x62, 0xc9, 0x45, 0xf9, 0xc9, 0xf9, 0x29, 0x99, 0x39, 0xa9, 0x7a, 0xc5, 0x45, 0x65, 0x7a, 0x30,
	0x59, 0x29, 0x4d, 0xb8, 0xb8, 0x7e, 0x71, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x7e, 0x56, 0x7e,
	0x92, 0x3e, 0xc4, 0x30, 0x10, 0x2b, 0x2b, 0x3f, 0x09, 0x62, 0x84, 0x52, 0x26, 0x17, 0x97, 0x2b,
	0x58, 0x5b, 0xaa, 0x6f, 0x71, 0xba, 0x90, 0x08, 0x17, 0x6b, 0x6a, 0x59, 0x6a, 0x5e, 0x89, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x84, 0x23, 0xa4, 0xcd, 0xc5, 0x52, 0x92, 0x58, 0x9c, 0x2d,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xae, 0x87, 0x6a, 0x2b, 0xc8, 0xac, 0x90, 0xc4, 0xe2,
	0xec, 0x20, 0xb0, 0x22, 0x21, 0x09, 0x2e, 0xf6, 0xa2, 0xd2, 0xbc, 0x8c, 0xfc, 0xe2, 0x12, 0x09,
	0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x37, 0x89, 0x0d, 0x6c, 0xa3, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x9f, 0xe7, 0x4c, 0x93, 0xd5, 0x00, 0x00, 0x00,
}
