FROM alpine

ENV GOPROXY https://goproxy.cn
WORKDIR /app
RUN apk update && apk --no-cache add ca-certificates curl vim python python3 nodejs npm go
COPY crocodile-linux-amd64 crocodile
CMD ["/app/crocodile","client","-c","core.toml"]

# docker build -t labulaka522/crocodile_worker . -f Dockerfile.worker
# docker run -v $PWD/core.toml:/app/core.toml labulaka522/crocodile:worker