// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/proto/core.proto

package crocodile_task

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskReq struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType             int32    `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskData             []byte   `protobuf:"bytes,3,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	Timeout              int32    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskReq) Reset()         { *m = TaskReq{} }
func (m *TaskReq) String() string { return proto.CompactTextString(m) }
func (*TaskReq) ProtoMessage()    {}
func (*TaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ea9561f1d738ba, []int{0}
}

func (m *TaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReq.Unmarshal(m, b)
}
func (m *TaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReq.Marshal(b, m, deterministic)
}
func (m *TaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReq.Merge(m, src)
}
func (m *TaskReq) XXX_Size() int {
	return xxx_messageInfo_TaskReq.Size(m)
}
func (m *TaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReq proto.InternalMessageInfo

func (m *TaskReq) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskReq) GetTaskType() int32 {
	if m != nil {
		return m.TaskType
	}
	return 0
}

func (m *TaskReq) GetTaskData() []byte {
	if m != nil {
		return m.TaskData
	}
	return nil
}

func (m *TaskReq) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type TaskResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrMsg               []byte   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	RespData             []byte   `protobuf:"bytes,3,opt,name=resp_data,json=respData,proto3" json:"resp_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResp) Reset()         { *m = TaskResp{} }
func (m *TaskResp) String() string { return proto.CompactTextString(m) }
func (*TaskResp) ProtoMessage()    {}
func (*TaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ea9561f1d738ba, []int{1}
}

func (m *TaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResp.Unmarshal(m, b)
}
func (m *TaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResp.Marshal(b, m, deterministic)
}
func (m *TaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResp.Merge(m, src)
}
func (m *TaskResp) XXX_Size() int {
	return xxx_messageInfo_TaskResp.Size(m)
}
func (m *TaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResp proto.InternalMessageInfo

func (m *TaskResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TaskResp) GetErrMsg() []byte {
	if m != nil {
		return m.ErrMsg
	}
	return nil
}

func (m *TaskResp) GetRespData() []byte {
	if m != nil {
		return m.RespData
	}
	return nil
}

type RegistryReq struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Hostname             string   `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Hostgroup            string   `protobuf:"bytes,6,opt,name=hostgroup,proto3" json:"hostgroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryReq) Reset()         { *m = RegistryReq{} }
func (m *RegistryReq) String() string { return proto.CompactTextString(m) }
func (*RegistryReq) ProtoMessage()    {}
func (*RegistryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ea9561f1d738ba, []int{2}
}

func (m *RegistryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryReq.Unmarshal(m, b)
}
func (m *RegistryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryReq.Marshal(b, m, deterministic)
}
func (m *RegistryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryReq.Merge(m, src)
}
func (m *RegistryReq) XXX_Size() int {
	return xxx_messageInfo_RegistryReq.Size(m)
}
func (m *RegistryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryReq proto.InternalMessageInfo

func (m *RegistryReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RegistryReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RegistryReq) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RegistryReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RegistryReq) GetHostgroup() string {
	if m != nil {
		return m.Hostgroup
	}
	return ""
}

type HeartbeatReq struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	RunningTask          []string `protobuf:"bytes,3,rep,name=running_task,json=runningTask,proto3" json:"running_task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatReq) Reset()         { *m = HeartbeatReq{} }
func (m *HeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartbeatReq) ProtoMessage()    {}
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ea9561f1d738ba, []int{3}
}

func (m *HeartbeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatReq.Unmarshal(m, b)
}
func (m *HeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatReq.Marshal(b, m, deterministic)
}
func (m *HeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatReq.Merge(m, src)
}
func (m *HeartbeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartbeatReq.Size(m)
}
func (m *HeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatReq proto.InternalMessageInfo

func (m *HeartbeatReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *HeartbeatReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *HeartbeatReq) GetRunningTask() []string {
	if m != nil {
		return m.RunningTask
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ea9561f1d738ba, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TaskReq)(nil), "crocodile.task.TaskReq")
	proto.RegisterType((*TaskResp)(nil), "crocodile.task.TaskResp")
	proto.RegisterType((*RegistryReq)(nil), "crocodile.task.RegistryReq")
	proto.RegisterType((*HeartbeatReq)(nil), "crocodile.task.HeartbeatReq")
	proto.RegisterType((*Empty)(nil), "crocodile.task.Empty")
}

func init() { proto.RegisterFile("core/proto/core.proto", fileDescriptor_80ea9561f1d738ba) }

var fileDescriptor_80ea9561f1d738ba = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x14, 0x24, 0x6d, 0x93, 0x34, 0x6f, 0xa3, 0x3d, 0x58, 0x5a, 0xad, 0xd5, 0xdd, 0x43, 0xc8, 0x29,
	0xa7, 0x54, 0x2a, 0x57, 0x24, 0x2e, 0x45, 0x2a, 0x07, 0x2e, 0xa6, 0x9c, 0x2b, 0x37, 0x79, 0x0a,
	0x56, 0x49, 0x6c, 0x6c, 0xa7, 0x52, 0x3e, 0x80, 0x1f, 0xe0, 0x8b, 0x91, 0xdd, 0xb4, 0xb4, 0x15,
	0x48, 0xdc, 0xe6, 0xcd, 0xd8, 0x99, 0x79, 0xe3, 0xc0, 0x53, 0x25, 0x35, 0x2e, 0x95, 0x96, 0x56,
	0x2e, 0x1d, 0x2c, 0x3d, 0x24, 0x8f, 0x95, 0x96, 0x95, 0xac, 0xc5, 0x77, 0x2c, 0x2d, 0x37, 0x87,
	0xfc, 0x08, 0xf1, 0x96, 0x9b, 0x03, 0xc3, 0x1f, 0xe4, 0x19, 0x62, 0x47, 0xed, 0x44, 0x4d, 0x83,
	0x2c, 0x28, 0x12, 0x16, 0xb9, 0xf1, 0x53, 0x4d, 0x5e, 0x20, 0xf1, 0x82, 0x1d, 0x14, 0xd2, 0x49,
	0x16, 0x14, 0x21, 0x9b, 0x3b, 0x62, 0x3b, 0x28, 0xbc, 0x88, 0x35, 0xb7, 0x9c, 0x4e, 0xb3, 0xa0,
	0x48, 0x4f, 0xe2, 0x9a, 0x5b, 0x4e, 0x28, 0xc4, 0x56, 0xb4, 0x28, 0x7b, 0x4b, 0x67, 0xfe, 0xde,
	0x79, 0xcc, 0xb7, 0x30, 0x3f, 0xf9, 0x1a, 0x45, 0x08, 0xcc, 0x2a, 0x59, 0xa3, 0x77, 0x0d, 0x99,
	0xc7, 0x2e, 0x0c, 0x6a, 0xbd, 0x6b, 0x4d, 0xe3, 0x1d, 0x53, 0x16, 0xa1, 0xd6, 0x9f, 0x4d, 0xe3,
	0xfc, 0x34, 0x1a, 0x75, 0xe3, 0xe7, 0x08, 0xe7, 0x97, 0xff, 0x0c, 0xe0, 0x81, 0x61, 0x23, 0x8c,
	0xd5, 0x83, 0x5b, 0xe9, 0x11, 0x26, 0x42, 0x8d, 0xdb, 0x4c, 0x84, 0x77, 0x52, 0x52, 0xdb, 0x71,
	0x09, 0x8f, 0xc9, 0x02, 0xe6, 0xdf, 0xa4, 0xb1, 0x1d, 0x6f, 0x91, 0x86, 0xfe, 0xe4, 0x65, 0x76,
	0xf9, 0x8f, 0xa8, 0x8d, 0x90, 0x9d, 0xcf, 0x9f, 0xb0, 0xf3, 0x48, 0x5e, 0x21, 0x71, 0xa7, 0x1a,
	0x2d, 0x7b, 0x45, 0x23, 0xaf, 0xfd, 0x21, 0xf2, 0xaf, 0x90, 0x6e, 0x90, 0x6b, 0xbb, 0x47, 0x6e,
	0xff, 0x37, 0xc7, 0x5b, 0x48, 0x75, 0xdf, 0x75, 0xa2, 0x6b, 0x76, 0xae, 0x3f, 0x3a, 0xcd, 0xa6,
	0x45, 0xc2, 0x1e, 0x46, 0xce, 0x95, 0x95, 0xc7, 0x10, 0x7e, 0x6c, 0x95, 0x1d, 0x56, 0x6b, 0x98,
	0x39, 0x82, 0xbc, 0x87, 0x98, 0xf5, 0x9d, 0x87, 0xcf, 0xe5, 0xed, 0xcb, 0x96, 0xe3, 0xb3, 0x2e,
	0xe8, 0xdf, 0x05, 0xa3, 0x56, 0xbf, 0x02, 0x48, 0x2e, 0x31, 0xc9, 0x1a, 0xd2, 0x73, 0x75, 0x1b,
	0x69, 0x2c, 0x79, 0xb9, 0xbf, 0x77, 0x55, 0xec, 0xe2, 0xe9, 0x5e, 0xf4, 0xb9, 0xf2, 0x37, 0xe4,
	0x03, 0x44, 0x5f, 0xb0, 0xab, 0x37, 0x7b, 0xf2, 0x7a, 0x7f, 0xe4, 0xba, 0x91, 0x7f, 0x7e, 0x60,
	0x1f, 0xf9, 0xff, 0xf4, 0xdd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x3b, 0x7e, 0x60, 0xc0,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskClient interface {
	RunTask(ctx context.Context, in *TaskReq, opts ...grpc.CallOption) (*TaskResp, error)
}

type taskClient struct {
	cc *grpc.ClientConn
}

func NewTaskClient(cc *grpc.ClientConn) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) RunTask(ctx context.Context, in *TaskReq, opts ...grpc.CallOption) (*TaskResp, error) {
	out := new(TaskResp)
	err := c.cc.Invoke(ctx, "/crocodile.task.Task/RunTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServer is the server API for Task service.
type TaskServer interface {
	RunTask(context.Context, *TaskReq) (*TaskResp, error)
}

// UnimplementedTaskServer can be embedded to have forward compatible implementations.
type UnimplementedTaskServer struct {
}

func (*UnimplementedTaskServer) RunTask(ctx context.Context, req *TaskReq) (*TaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTask not implemented")
}

func RegisterTaskServer(s *grpc.Server, srv TaskServer) {
	s.RegisterService(&_Task_serviceDesc, srv)
}

func _Task_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crocodile.task.Task/RunTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).RunTask(ctx, req.(*TaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Task_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crocodile.task.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunTask",
			Handler:    _Task_RunTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/proto/core.proto",
}

// HeartbeatClient is the client API for Heartbeat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HeartbeatClient interface {
	// registry host
	RegistryHost(ctx context.Context, in *RegistryReq, opts ...grpc.CallOption) (*Empty, error)
	SendHb(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*Empty, error)
}

type heartbeatClient struct {
	cc *grpc.ClientConn
}

func NewHeartbeatClient(cc *grpc.ClientConn) HeartbeatClient {
	return &heartbeatClient{cc}
}

func (c *heartbeatClient) RegistryHost(ctx context.Context, in *RegistryReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/crocodile.task.Heartbeat/RegistryHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heartbeatClient) SendHb(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/crocodile.task.Heartbeat/SendHb", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartbeatServer is the server API for Heartbeat service.
type HeartbeatServer interface {
	// registry host
	RegistryHost(context.Context, *RegistryReq) (*Empty, error)
	SendHb(context.Context, *HeartbeatReq) (*Empty, error)
}

// UnimplementedHeartbeatServer can be embedded to have forward compatible implementations.
type UnimplementedHeartbeatServer struct {
}

func (*UnimplementedHeartbeatServer) RegistryHost(ctx context.Context, req *RegistryReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistryHost not implemented")
}
func (*UnimplementedHeartbeatServer) SendHb(ctx context.Context, req *HeartbeatReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHb not implemented")
}

func RegisterHeartbeatServer(s *grpc.Server, srv HeartbeatServer) {
	s.RegisterService(&_Heartbeat_serviceDesc, srv)
}

func _Heartbeat_RegistryHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartbeatServer).RegistryHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crocodile.task.Heartbeat/RegistryHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartbeatServer).RegistryHost(ctx, req.(*RegistryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Heartbeat_SendHb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartbeatServer).SendHb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crocodile.task.Heartbeat/SendHb",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartbeatServer).SendHb(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Heartbeat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crocodile.task.Heartbeat",
	HandlerType: (*HeartbeatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistryHost",
			Handler:    _Heartbeat_RegistryHost_Handler,
		},
		{
			MethodName: "SendHb",
			Handler:    _Heartbeat_SendHb_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/proto/core.proto",
}
