// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/actuator/actuator.proto

package crocodile_srv_actuator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Actuat struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Address              []*Addr  `protobuf:"bytes,3,rep,name=address,proto3" json:"address"`
	Createdby            string   `protobuf:"bytes,4,opt,name=createdby,proto3" json:"createdby"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Actuat) Reset()         { *m = Actuat{} }
func (m *Actuat) String() string { return proto.CompactTextString(m) }
func (*Actuat) ProtoMessage()    {}
func (*Actuat) Descriptor() ([]byte, []int) {
	return fileDescriptor_9796c805fa3f57fd, []int{0}
}

func (m *Actuat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actuat.Unmarshal(m, b)
}
func (m *Actuat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actuat.Marshal(b, m, deterministic)
}
func (m *Actuat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actuat.Merge(m, src)
}
func (m *Actuat) XXX_Size() int {
	return xxx_messageInfo_Actuat.Size(m)
}
func (m *Actuat) XXX_DiscardUnknown() {
	xxx_messageInfo_Actuat.DiscardUnknown(m)
}

var xxx_messageInfo_Actuat proto.InternalMessageInfo

func (m *Actuat) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Actuat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Actuat) GetAddress() []*Addr {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Actuat) GetCreatedby() string {
	if m != nil {
		return m.Createdby
	}
	return ""
}

type Response struct {
	Actuators []*Actuat `protobuf:"bytes,2,rep,name=actuators,proto3" json:"actuators"`
	// 所有注册的worker的IP
	ExecutorIps []string `protobuf:"bytes,3,rep,name=executorIps,proto3" json:"executorIps"`
	//
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9796c805fa3f57fd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetActuators() []*Actuat {
	if m != nil {
		return m.Actuators
	}
	return nil
}

func (m *Response) GetExecutorIps() []string {
	if m != nil {
		return m.ExecutorIps
	}
	return nil
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Addr struct {
	// IP地址
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip"`
	// 状态
	Online               bool     `protobuf:"varint,2,opt,name=online,proto3" json:"online"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addr) Reset()         { *m = Addr{} }
func (m *Addr) String() string { return proto.CompactTextString(m) }
func (*Addr) ProtoMessage()    {}
func (*Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_9796c805fa3f57fd, []int{2}
}

func (m *Addr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addr.Unmarshal(m, b)
}
func (m *Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addr.Marshal(b, m, deterministic)
}
func (m *Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addr.Merge(m, src)
}
func (m *Addr) XXX_Size() int {
	return xxx_messageInfo_Addr.Size(m)
}
func (m *Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_Addr.DiscardUnknown(m)
}

var xxx_messageInfo_Addr proto.InternalMessageInfo

func (m *Addr) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Addr) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func init() {
	proto.RegisterType((*Actuat)(nil), "crocodile.srv.actuator.Actuat")
	proto.RegisterType((*Response)(nil), "crocodile.srv.actuator.Response")
	proto.RegisterType((*Addr)(nil), "crocodile.srv.actuator.Addr")
}

func init() { proto.RegisterFile("proto/actuator/actuator.proto", fileDescriptor_9796c805fa3f57fd) }

var fileDescriptor_9796c805fa3f57fd = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0xa4, 0x7f, 0xbe, 0xe6, 0x06, 0x8a, 0xcc, 0xa2, 0x04, 0xa9, 0x12, 0xb2, 0xca,
	0x6a, 0x84, 0x0a, 0xae, 0xdc, 0x84, 0x2a, 0xe2, 0x4e, 0x07, 0x71, 0x3f, 0x9d, 0xb9, 0x68, 0x20,
	0x66, 0xc2, 0xcc, 0x54, 0x74, 0xe3, 0xc2, 0x97, 0xf2, 0xf5, 0x24, 0xb7, 0x4d, 0xeb, 0xc2, 0xe2,
	0x26, 0xbb, 0x33, 0x67, 0x92, 0xdf, 0x3d, 0xf7, 0x84, 0xc0, 0x49, 0x63, 0x8d, 0x37, 0x67, 0x52,
	0xf9, 0xb5, 0xf4, 0xc6, 0xee, 0x04, 0x27, 0x9f, 0xcd, 0x94, 0x35, 0xca, 0xe8, 0xb2, 0x42, 0xee,
	0xec, 0x2b, 0xef, 0x6e, 0xb3, 0xcf, 0x00, 0xc6, 0x05, 0x1d, 0xd8, 0x14, 0xc2, 0x52, 0x27, 0x41,
	0x1a, 0xe4, 0x23, 0x11, 0x96, 0x9a, 0x31, 0x18, 0xd6, 0xf2, 0x05, 0x93, 0x30, 0x0d, 0xf2, 0x48,
	0x90, 0x66, 0x17, 0xf0, 0x5f, 0x6a, 0x6d, 0xd1, 0xb9, 0x64, 0x90, 0x0e, 0xf2, 0x78, 0x31, 0xe7,
	0xbf, 0x83, 0x79, 0xa1, 0xb5, 0x15, 0xdd, 0xc3, 0x6c, 0x0e, 0x91, 0xb2, 0x28, 0x3d, 0xea, 0xd5,
	0x7b, 0x32, 0x24, 0xe0, 0xde, 0xc8, 0x3e, 0x60, 0x22, 0xd0, 0x35, 0xa6, 0x76, 0xc8, 0x2e, 0x21,
	0xea, 0x18, 0x2e, 0x09, 0x69, 0xc6, 0xe9, 0xc1, 0x19, 0x24, 0xc4, 0xfe, 0x05, 0x96, 0x42, 0x8c,
	0x6f, 0xa8, 0xd6, 0xde, 0xd8, 0xdb, 0x66, 0x93, 0x31, 0x12, 0x3f, 0xad, 0x76, 0x2b, 0x65, 0x34,
	0x52, 0x88, 0x91, 0x20, 0x9d, 0x71, 0x18, 0xb6, 0x71, 0xa9, 0x81, 0x86, 0x1a, 0x88, 0x44, 0x58,
	0x36, 0x6c, 0x06, 0x63, 0x53, 0x57, 0x65, 0xbd, 0xe9, 0x60, 0x22, 0xb6, 0xa7, 0xc5, 0xd7, 0x00,
	0x26, 0xc5, 0x76, 0x26, 0x7b, 0x80, 0xe9, 0x92, 0x36, 0xd9, 0x39, 0x7f, 0xe4, 0x3d, 0x4e, 0x0f,
	0xdd, 0x77, 0x25, 0x64, 0xff, 0x5a, 0xea, 0x15, 0x56, 0xd8, 0x3f, 0x75, 0xf9, 0x2c, 0xeb, 0xa7,
	0x7e, 0xa9, 0xf7, 0x10, 0xdf, 0xa0, 0xef, 0x15, 0xf9, 0x08, 0x47, 0x2d, 0xb2, 0xaa, 0xae, 0xbb,
	0x4f, 0x77, 0xd7, 0x07, 0x77, 0x35, 0xa6, 0xbf, 0xe1, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x24,
	0x3f, 0x6e, 0x7f, 0x2e, 0x03, 0x00, 0x00,
}
