// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package crocodile_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Forbid               bool     `protobuf:"varint,6,opt,name=forbid,proto3" json:"forbid,omitempty"`
	Super                bool     `protobuf:"varint,7,opt,name=super,proto3" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetForbid() bool {
	if m != nil {
		return m.Forbid
	}
	return false
}

func (m *User) GetSuper() bool {
	if m != nil {
		return m.Super
	}
	return false
}

type Response struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "crocodile.srv.auth.User")
	proto.RegisterType((*Response)(nil), "crocodile.srv.auth.Response")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xbd, 0x4e, 0xfb, 0x30,
	0x14, 0xc5, 0xff, 0x49, 0x93, 0x7e, 0xdc, 0xbf, 0x60, 0xb0, 0x00, 0x59, 0x15, 0x43, 0xd4, 0x29,
	0x93, 0x91, 0xca, 0x13, 0xa0, 0xf2, 0xb1, 0x74, 0xb2, 0xc4, 0x03, 0xb8, 0xf5, 0xa5, 0xb1, 0x48,
	0x73, 0x23, 0xdb, 0x29, 0xef, 0xc4, 0xc8, 0x13, 0x22, 0x3b, 0x2d, 0x0b, 0x30, 0x85, 0xc5, 0xf2,
	0xef, 0x9e, 0xab, 0xa3, 0x73, 0x2c, 0xc3, 0x65, 0x6b, 0xc9, 0xd3, 0x8d, 0xea, 0x7c, 0x15, 0x0f,
	0x11, 0x99, 0xb1, 0xad, 0xa5, 0x2d, 0x69, 0x53, 0xa3, 0x70, 0xf6, 0x20, 0x82, 0xb2, 0x78, 0x4f,
	0x20, 0x7b, 0x76, 0x68, 0xd9, 0x39, 0xa4, 0x46, 0xf3, 0xa4, 0x48, 0xca, 0x33, 0x99, 0x1a, 0xcd,
	0xe6, 0x30, 0xed, 0x1c, 0xda, 0x46, 0xed, 0x91, 0xa7, 0x45, 0x52, 0xce, 0xe4, 0x17, 0x07, 0xad,
	0x55, 0xce, 0xbd, 0x91, 0xd5, 0x7c, 0xd4, 0x6b, 0x27, 0x66, 0x17, 0x90, 0xe3, 0x5e, 0x99, 0x9a,
	0x67, 0x51, 0xe8, 0x81, 0x5d, 0xc1, 0x58, 0x1d, 0x94, 0x57, 0x96, 0xe7, 0x71, 0x7c, 0xa4, 0x30,
	0x7f, 0x21, 0xbb, 0x31, 0x9a, 0x8f, 0x8b, 0xa4, 0x9c, 0xca, 0x23, 0x05, 0x17, 0xd7, 0xb5, 0x68,
	0xf9, 0x24, 0x8e, 0x7b, 0x58, 0x68, 0x98, 0x4a, 0x74, 0x2d, 0x35, 0x0e, 0xc3, 0x86, 0xa7, 0x57,
	0x6c, 0x62, 0xe4, 0x99, 0xec, 0x81, 0x09, 0xc8, 0x43, 0x4a, 0xc7, 0xd3, 0x62, 0x54, 0xfe, 0x5f,
	0x72, 0xf1, 0xbd, 0xb2, 0x08, 0x75, 0x65, 0xbf, 0xc6, 0x18, 0x64, 0x5b, 0xd2, 0x18, 0x5b, 0xe4,
	0x32, 0xde, 0x97, 0x1f, 0x23, 0xc8, 0xee, 0x3a, 0x5f, 0xb1, 0x47, 0x80, 0x95, 0x45, 0xe5, 0x31,
	0x3e, 0xd0, 0xaf, 0x5e, 0xf3, 0xeb, 0x9f, 0x94, 0x53, 0xd0, 0xc5, 0xbf, 0xe8, 0x53, 0xa9, 0x66,
	0xf7, 0x07, 0x3e, 0xf7, 0x58, 0xe3, 0xe0, 0x3c, 0x2b, 0x98, 0x3c, 0xa1, 0x1f, 0x68, 0xf2, 0x00,
	0xb3, 0x35, 0xed, 0x4c, 0x33, 0xbc, 0xd3, 0x9a, 0x76, 0xd4, 0x0d, 0x8c, 0xb3, 0x19, 0xc7, 0x2f,
	0x7e, 0xfb, 0x19, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x52, 0x5a, 0x8d, 0xfb, 0x02, 0x00, 0x00,
}
