BEGIN;
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/hostgroup*', '(GET)|(POST)|(DELETE)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Normal', '/api/v1/hostgroup*', '(GET)|(POST)|(DELETE)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Guest', '/api/v1/hostgroup*', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/task*', '(GET)|(POST)|(DELETE)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Normal', '/api/v1/task*', '(GET)|(POST)|(DELETE)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Guest', '/api/v1/task*', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/host*', '(GET)|(POST)|(DELETE)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Normal', '/api/v1/host*', '(GET)|(POST)|(DELETE)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Guest', '/api/v1/host*', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/user/info', '(GET)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Normal', '/api/v1/user/info', '(GET)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Guest', '/api/v1/user/info', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/user/select', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Normal', '/api/v1/user/select', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Guest', '/api/v1/user/select', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/user/registry', '(POST)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/user/all', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/user/admin', '(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/user/alarmstatus', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Normal', '/api/v1/user/alarmstatus', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Guest', '/api/v1/user/alarmstatus', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/user/operate', '(GET)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Admin', '/api/v1/notify', '(GET)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Normal', '/api/v1/notify', '(GET)|(PUT)', '', '', '');
INSERT INTO "casbin_rule" VALUES ('p', 'Guest', '/api/v1/notify', '(GET)', '', '', '');
COMMIT;